CREATE TABLE player(
   id     int  NOT NULL PRIMARY KEY 
  ,name   VARCHAR(250) NOT NULL
  ,role   VARCHAR(250) NOT NULL
  ,amount int  NOT NULL
  ,team   VARCHAR(250) NOT NULL
  ,label  VARCHAR(5) NOT NULL
);
INSERT INTO player(id,name,role,amount,team,label) VALUES (1001,'Ben Stokes','All-Rounder',162500000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1002,'Ravindra Jadeja','All-Rounder',160000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1003,'Deepak Chahar','Bowler',140000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1004,'MS Dhoni','Wicket-Keeper',120000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1005,'Moeen Ali','All-Rounder',80000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1006,'Ambati Rayudu','Batter',67500000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1007,'Ruturaj Gaikwad','Batter',60000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1008,'Shivam Dube','All-Rounder',40000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1009,'Mitchell Santner','All-Rounder',19000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1010,'Rajvardhan Hangargekar','Bowler',15000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1011,'Prashant Solanki','Bowler',12000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1012,'Kyle Jamieson','Bowler',10000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1013,'Devon Conway','Batter',10000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1014,'Maheesh Theekshana','Bowler',7000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1015,'Nishant Sindhu','All-Rounder',6000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1016,'Ajinkya Rahane','Batter',5000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1017,'Dwaine Pretorius','All-Rounder',5000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1018,'Matheesha Pathirana','Bowler',2000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1019,'Mukesh Choudhary','Bowler',2000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1020,'Shaik Rasheed','Batter',2000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1021,'Simarjeet Singh','Bowler',2000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1022,'Subhranshu Senapati','Batter',2000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1023,'Bhagath Varma','All-Rounder',2000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1024,'Ajay Mandal','All-Rounder',2000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1025,'Tushar Deshpande','Bowler',2000000,'Chennai Super Kings','CSK');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1026,'Rishabh Pant','Wicket-Keeper',160000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1027,'Axar Patel','All-Rounder',120000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1028,'Prithvi Shaw','Batter',80000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1029,'Mitchell Marsh','All-Rounder',65000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1030,'Anrich Nortje','Bowler',65000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1031,'David Warner','Batter',62500000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1032,'Mukesh Kumar','Bowler',55000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1033,'Khaleel Ahmed','Bowler',52500000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1034,'Rilee Rossouw','Batter',46000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1035,'Chetan Sakariya','Bowler',42000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1036,'Rovman Powell','Batter',28000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1037,'Manish Pandey','Batter',24000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1038,'Mustafizur Rahman','Bowler',20000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1039,'Kuldeep Yadav','Bowler',20000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1040,'Philip Salt','Wicket-Keeper',20000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1041,'Kamlesh Nagarkoti','Bowler',11000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1042,'Lalit Yadav','All-Rounder',6500000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1043,'Ishant Sharma','Bowler',5000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1044,'Lungi Ngidi','Bowler',5000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1045,'Pravin Dubey','Bowler',5000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1046,'Yash Dhull','Batter',5000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1047,'Ripal Patel','Batter',2000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1048,'Aman Khan','All-Rounder',2000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1049,'Vicky Ostwal','Bowler',2000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1050,'Sarfaraz Khan','Batter',2000000,'Delhi Capitals','DC');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1051,'Hardik Pandya','All-Rounder',150000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1052,'Rashid Khan','Bowler',150000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1053,'Rahul Tewatia','All-Rounder',90000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1054,'Shubman Gill','Batter',80000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1055,'Mohammad Shami','Bowler',62500000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1056,'Shivam Mavi','Bowler',60000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1057,'Josh Little','Bowler',44000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1058,'Yash Dayal','Bowler',32000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1059,'Sai Kishore','All-Rounder',30000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1060,'David Miller','Batter',30000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1061,'Abhinav Manohar','Batter',26000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1062,'Alzarri Joseph','Bowler',24000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1063,'Matthew Wade','Wicket-Keeper',24000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1064,'Kane Williamson','Batter',20000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1065,'Wriddhiman Saha','Wicket-Keeper',19000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1066,'Jayant Yadav','Bowler',17000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1067,'Vijay Shankar','All-Rounder',14000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1068,'Srikar Bharat','Wicket-Keeper',12000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1069,'Mohit Sharma','Bowler',5000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1070,'Odean Smith','All-Rounder',5000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1071,'Noor Ahmad','Bowler',3000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1072,'Darshan Nalkande','Bowler',2000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1073,'Urvil Patel','Wicket-Keeper',2000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1074,'Sai Sudharsan','Batter',2000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1075,'Pradeep Sangwan','Bowler',2000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1076,'Andre Russell','All-Rounder',160000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1077,'Shreyas Iyer','Batter',122500000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1078,'Varun Chakaravarthy','Bowler',120000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1079,'Shardul Thakur','Bowler',107500000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1080,'Lockie Ferguson','Bowler',100000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1081,'Venkatesh Iyer','All-Rounder',80000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1082,'Nitish Rana','Batter',80000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1083,'Sunil Narine','All-Rounder',60000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1084,'Umesh Yadav','Bowler',20000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1085,'Shakib Al Hasan','All-Rounder',15000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1086,'Tim Southee','Bowler',15000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1087,'David Wiese','All-Rounder',10000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1088,'Narayan Jagadeesan','Wicket-Keeper',9000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1089,'Vaibhav Arora','Bowler',6000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1090,'Rinku Singh','Batter',5500000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1091,'Mandeep Singh','Batter',5000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1092,'Litton Das','Wicket-Keeper',5000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1093,'Rahmanullah Gurbaz','Wicket-Keeper',5000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1094,'Suyash Sharma','Bowler',2000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1095,'Harshit Rana','Bowler',2000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1096,'Anukul Roy','All-Rounder',2000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1097,'Kulwant Khejroliya','Bowler',2000000,'Gujarat Titans','GT');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1098,'KL Rahul','Batter',170000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1099,'Nicholas Pooran','Wicket-Keeper',160000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1100,'Avesh Khan','Bowler',100000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1101,'Marcus Stoinis','All-Rounder',100000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1102,'Krunal Pandya','All-Rounder',82500000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1103,'Mark Wood','Bowler',75000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1104,'Quinton de Kock','Wicket-Keeper',67500000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1105,'Deepak Hooda','All-Rounder',57500000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1106,'Ravi Bishnoi','Bowler',40000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1107,'Krishnappa Gowtham','All-Rounder',9000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1108,'Daniel Sams','All-Rounder',7500000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1109,'Amit Mishra','Bowler',5000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1110,'Jaydev Unadkat','Bowler',5000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1111,'Kyle Mayers','Batter',5000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1112,'Naveen-ul-Haq','Bowler',5000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1113,'Romario Shepherd','All-Rounder',5000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1114,'Yash Thakur','Bowler',4500000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1115,'Mohsin Khan','Bowler',2000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1116,'Ayush Badoni','Batter',2000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1117,'Karan Sharma','All-Rounder',2000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1118,'Yudhvir Singh','All-Rounder',2000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1119,'Mayank Yadav','Bowler',2000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1120,'Prerak Mankad','All-Rounder',2000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1121,'Swapnil Singh','All-Rounder',2000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1122,'Manan Vohra','Batter',2000000,'Lucknow Super Giants','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1123,'Cameron Green','All-Rounder',175000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1124,'Rohit Sharma','Batter',160000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1125,'Ishan Kishan','Wicket-Keeper',152500000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1126,'Jasprit Bumrah','Bowler',120000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1127,'Tim David','Batter',82500000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1128,'Jofra Archer','Bowler',80000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1129,'Suryakumar Yadav','Batter',80000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1130,'Dewald Brevis','All-Rounder',30000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1131,'Tilak Varma','Batter',17000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1132,'Jhye Richardson','Bowler',15000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1133,'Jason Behrendorff','Bowler',7500000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1134,'Piyush Chawla','Bowler',5000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1135,'Arjun Tendulkar','Bowler',3000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1136,'Kumar Kartikeya','Bowler',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1137,'Duan Jansen','Bowler',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1138,'Arshad Khan','Bowler',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1139,'Hrithik Shokeen','Bowler',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1140,'Akash Madhwal','Bowler',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1141,'Raghav Goyal','Bowler',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1142,'Tristan Stubbs','Batter',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1143,'Nehal Wadhera','All-Rounder',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1144,'Shams Mulani','All-Rounder',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1145,'Ramandeep Singh','Batter',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1146,'Vishnu Vinod','Wicket-Keeper',2000000,'Mumbai Indians','LSG');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1147,'Sam Curran','All-Rounder',185000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1148,'Liam Livingstone','All-Rounder',115000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1149,'Kagiso Rabada','Bowler',92500000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1150,'Shahrukh Khan','Batter',90000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1151,'Shikhar Dhawan','Batter',82500000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1152,'Jonny Bairstow','Wicket-Keeper',67500000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1153,'Rahul Chahar','Bowler',52500000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1154,'Arshdeep Singh','Bowler',40000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1155,'Harpreet Brar','Bowler',38000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1156,'Raj Bawa','All-Rounder',20000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1157,'Nathan Ellis','Bowler',7500000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1158,'Prabhsimran Singh','Wicket-Keeper',6000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1159,'Rishi Dhawan','All-Rounder',5500000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1160,'Sikandar Raza','All-Rounder',5000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1161,'Bhanuka Rajapaksa','Batter',5000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1162,'Harpreet Singh Bhatia','Batter',4000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1163,'Atharva Taide','Batter',2000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1164,'Mohit Rathee','All-Rounder',2000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1165,'Shivam Singh','All-Rounder',2000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1166,'Vidhwath Kaverappa','Bowler',2000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1167,'Jitesh Sharma','Wicket-Keeper',2000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1168,'Baltej Singh','Bowler',2000000,'Punjab Kings','KXIP');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1169,'Virat Kohli','Batter',150000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1170,'Glenn Maxwell','All-Rounder',110000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1171,'Harshal Patel','Bowler',107500000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1172,'Wanindu Hasaranga','All-Rounder',107500000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1173,'Josh Hazlewood','Bowler',77500000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1174,'Faf du Plessis','Batter',70000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1175,'Mohammed Siraj','Bowler',70000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1176,'Dinesh Karthik','Wicket-Keeper',55000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1177,'Anuj Rawat','Wicket-Keeper',34000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1178,'Will Jacks','Batter',32000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1179,'Shahbaz Ahmed','All-Rounder',24000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1180,'David Willey','Bowler',20000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1181,'Reece Topley','Bowler',19000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1182,'Mahipal Lomror','All-Rounder',9500000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1183,'Finn Allen','Batter',8000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1184,'Siddarth Kaul','Bowler',7500000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1185,'Rajan Kumar','Bowler',7000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1186,'Avinash Singh','Bowler',6000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1187,'Karn Sharma','Bowler',5000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1188,'Suyash Prabhudessai','Batter',3000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1189,'Sonu Yadav','All-Rounder',2000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1190,'Manoj Bhandage','All-Rounder',2000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1191,'Akash Deep','Bowler',2000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1192,'Himanshu Sharma','Bowler',2000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1193,'Rajat Patidar','Batter',2000000,'Royal Challengers Bangalore','RCB');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1194,'Sanju Samson','Wicket-Keeper',140000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1195,'Prasidh Krishna','Bowler',100000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1196,'Jos Buttler','Wicket-Keeper',100000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1197,'Shimron Hetmyer','Batter',85000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1198,'Trent Boult','Bowler',80000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1199,'Devdutt Padikkal','Batter',77500000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1200,'Yuzvendra Chahal','Bowler',65000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1201,'Jason Holder','All-Rounder',57500000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1202,'Ravichandran Ashwin','All-Rounder',50000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1203,'Yashasvi Jaiswal','Batter',40000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1204,'Riyan Parag','Batter',38000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1205,'Navdeep Saini','Bowler',26000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1206,'Adam Zampa','Bowler',15000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1207,'Joe Root','Batter',10000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1208,'Obed McCoy','Bowler',7500000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1209,'D Ferreira','Wicket-Keeper',5000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1210,'KM Asif','Bowler',3000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1211,'KC Cariappa','Bowler',3000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1212,'Kuldeep Sen','Bowler',2000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1213,'Dhruv Jurel','Wicket-Keeper',2000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1214,'Kunal Singh Rathore','Wicket-Keeper',2000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1215,'Abdul Basith','All-Rounder',2000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1216,'Akash Vasisht','All-Rounder',2000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1217,'Murugan Ashwin','Bowler',2000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1218,'Kuldip Yadav','Bowler',2000000,'Rajasthan Royals','RR');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1219,'Harry Brook','Batter',132500000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1220,'Washington Sundar','All-Rounder',87500000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1221,'Rahul Tripathi','Batter',85000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1222,'Mayank Agarwal','Batter',82500000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1223,'Abhishek Sharma','All-Rounder',65000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1224,'Heinrich Klaasen','Wicket-Keeper',52500000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1225,'Bhuvneshwar Kumar','Bowler',42000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1226,'Marco Jansen','Bowler',42000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1227,'Abdul Samad','Batter',40000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1228,'Umran Malik','Bowler',40000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1229,'T Natarajan','Bowler',40000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1230,'Kartik Tyagi','Bowler',40000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1231,'Aiden Markram','Batter',26000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1232,'Vivrant Sharma','All-Rounder',26000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1233,'Adil Rashid','Bowler',20000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1234,'Mayank Dagar','All-Rounder',18000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1235,'Glenn Phillips','Wicket-Keeper',15000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1236,'Akeal Hosein','Bowler',10000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1237,'Mayank Markande','Bowler',5000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1238,'Fazalhaq Farooqi','Bowler',5000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1239,'Upendra Yadav','Wicket-Keeper',2500000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1240,'Sanvir Singh','All-Rounder',2000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1241,'Samarth Vyas','All-Rounder',2000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1242,'Nitish Kumar Reddy','Wicket-Keeper',2000000,'Sunrisers Hyderabad','SRH');
INSERT INTO player(id,name,role,amount,team,label) VALUES (1243,'Anmolpreet Singh','Batter',2000000,'Sunrisers Hyderabad','SRH');